###
POST http://localhost:4000/api/posts
Content-Type: application/json

{
  "title": "title",
  "body": "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
  "tags": ["tag", "array", "post"]
}
###

### 
GET http://localhost:4000/api/posts
###

###
GET http://localhost:4000/api/posts/5cae153c6c861d1885136a4a
###
###
DELETE http://localhost:4000/api/posts/5cae153c6c861d1885136a4a
###
###
PATCH http://localhost:4000/api/posts/5cae17880326551e35e8b4c9
Content-Type: application/json

{
  "title": "change title"
}
####

POST http://localhost:4000/api/posts
Content-Type: application/json

{
  "title": "title",
  "body": "contents"
}
#####